import {useState,useEffect} from 'react';import {createRoot} from 'react-dom/client';import type {User} from '@supabase/supabase-js';import Atelier from './Atelier';import {supabase,configured,signIn,signOut,checkAccess} from './supabase';import './style.css';
function App(){
 const [user,setUser]=useState<User|null>(null),[ready,setReady]=useState(!configured),[demo,setDemo]=useState(false),[error,setError]=useState(''),[allowed,setAllowed]=useState(false),[checking,setChecking]=useState(false),[email,setEmail]=useState(''),[sending,setSending]=useState(false),[sent,setSent]=useState(false);
 useEffect(()=>{if(!supabase)return;let active=true;const query=new URLSearchParams(window.location.search);if(query.get('error')){setError('Le lien de connexion est invalide ou expiré. Demandez un nouveau lien.');window.history.replaceState({},'',window.location.pathname);}supabase.auth.getSession().then(({data,error})=>{if(!active)return;if(error)setError('La connexion a échoué. Réessayez.');setUser(data.session?.user??null);setReady(true)});const {data}=supabase.auth.onAuthStateChange((_event,session)=>{if(active){setUser(session?.user??null);setReady(true)}});return()=>{active=false;data.subscription.unsubscribe()};},[]);
 useEffect(()=>{let active=true;setAllowed(false);if(!user){setChecking(false);return;}setChecking(true);checkAccess().then(ok=>{if(active)setAllowed(ok)}).catch(()=>{if(active)setError('Vérification de l’accès impossible. Réessayez en vous reconnectant.')}).finally(()=>{if(active)setChecking(false)});return()=>{active=false}},[user]);
 if(!ready||checking)return <div className="login"><p role="status">Vérification de la connexion…</p></div>;
 if(allowed||demo)return <Atelier key={allowed?user?.id:'demo'} email={allowed?user?.email??'':''} authorized={allowed} onExit={async()=>{if(demo){setDemo(false);return}try{await signOut()}catch{setError('Déconnexion impossible. Réessayez.')}}}/>;
 return <div className="login"><section className="login-card"><span className="login-logo">LA MACHE <small>ATELIER</small></span><h1>Vos ateliers,<br/>au même endroit.</h1><p>Maintenance des systèmes pédagogiques, demandes d’achat et planning des TP.</p>{!configured&&<div className="setup-note">La connexion n’est pas encore configurée. Un aperçu est disponible ci-dessous.</div>}{user&&!allowed&&<div className="error">Ce compte n’est pas autorisé. Contactez le responsable de l’atelier.</div>}{error&&<div className="error" role="alert">{error}</div>}
 <form className="email-login" onSubmit={async e=>{e.preventDefault();setError('');setSending(true);setSent(false);try{if(user)await signOut();await signIn(email);setSent(true)}catch(e:any){setError(e.message?.includes('adresse @lamache.org')?e.message:'Envoi impossible. Vérifiez votre adresse ou contactez le responsable de l’atelier.')}finally{setSending(false)}}}>
 <label htmlFor="login-email">Adresse professionnelle</label><input id="login-email" type="email" autoComplete="email" required placeholder="prenom.nom@lamache.org" value={email} onChange={e=>{setEmail(e.target.value);setSent(false)}}/><button className="primary" disabled={!configured||sending}>{sending?'Envoi en cours…':'Recevoir un lien de connexion'}</button>
 </form>{sent&&<p className="success" role="status">Si votre adresse est autorisée, vous recevrez un lien. Ouvrez-le dans ce navigateur et vérifiez vos courriers indésirables.</p>}<small>Accès réservé aux enseignants autorisés. Aucun mot de passe à saisir.</small><button className="text-button" onClick={()=>setDemo(true)}>Consulter l’aperçu avec des exemples</button></section></div>}
 createRoot(document.getElementById('root')!).render(<App/>);
